server:
  port: 8040

spring:
  application:
    name: mall-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.3:9001
        #namespace: 5ac81613-77c1-4839-99ce-2fd17f1de7f3
        #cluster-name: BJ
        group: azhshop
        #ephemeral: false


management:
  endpoints:
    web:
      exposure:
        include: '*'