server:
  port: 8040

spring:
  application:
    name: mall-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.3:80
        cluster-name: SH
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  # 开启 ribbon 饥饿加载
  eager-load:
    enabled: true
    clients: mall-user