server:
  port: 8040

spring:
  application:
    name: mall-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      server-addr: 10.211.55.3:80


management:
  endpoints:
    web:
      exposure:
        include: '*'