server:
  port: 8040

spring:
  application:
    name: mall-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.3:80
        cluster-name: BJ
        group: user
        namespace: 17694b24-9c06-4b87-aae0-9acb2b7dfc3b


management:
  endpoints:
    web:
      exposure:
        include: '*'